### ISSUE TITLE
Opis użycia

### ISSUE THREAD

**Issue by Kobzi** [RadoslawKaminski/CzaryCzary#1]
Cześć, może chcesz dodać jakiś opis użycia tego skryptu. Wrzucając bazę i skrypt normalnie do konsoli w odpalonym egzaminie, nic to nie robi. Chyba że używa się tego skryptu inaczej. Próbowałem tak z 10min temu i nic to nie dało

**Comment by Kobzi** [comment]
Błąd w Firefox: TypeError: questions[exam][chapter] is undefined
Błąd w Chrome: Uncaught TypeError: Cannot read property 'forEach' of undefined at HTMLDocument.<anonymous> (<anonymous>:70:28)

**Comment by RadoslawKaminski** [comment]
Jest to wtyczka. Aby program zadziałał, musi być naciśnięta odpowiednia sekwencja klawiszy. Jeżeli nadal jesteś zainteresowany, odezwij się do mnie na:
fb: https://www.facebook.com/profile.php?id=100004614602288
email: r.kaminski@otsu.pl
lub drugi: radoslaw.kaminski.mail@gmail.com
Jednak najszybciej mnie znajdziesz na fb :)
